import { useLocation } from "wouter";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft, AlertTriangle } from "lucide-react";
import { APP_NAME } from "@/lib/brand";

/**
 * A starting point, not a privacy policy.
 *
 * The original of this page described data practices this code does not have —
 * third-party authentication, a named company, a real contact address. Shipping
 * that in a template is worse than shipping nothing: someone deploys it
 * unchanged and now has a policy that misdescribes their own service.
 *
 * What follows instead is an accurate description of what this code actually
 * stores, which is the part only the code can tell you. The obligations — who
 * you are, which laws apply to you, how someone reaches you — are yours to fill
 * in, with advice from someone qualified to give it.
 */
const PrivacyPolicy = () => {
  const [, setLocation] = useLocation();

  return (
    <div className="container mx-auto px-4 py-6 max-w-4xl">
      <Button
        variant="ghost"
        size="sm"
        className="mb-4 text-gray-400 hover:text-primary"
        onClick={() => setLocation("/")}
      >
        <ArrowLeft className="h-4 w-4 mr-2" />
        Back to Home
      </Button>

      <Card className="bg-dark-light border-dark-lighter">
        <CardHeader>
          <CardTitle className="text-2xl font-bold text-center">Privacy Policy</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6 text-gray-300">
          <div className="flex gap-3 rounded-lg border border-amber-500/40 bg-amber-500/10 p-4">
            <AlertTriangle className="h-5 w-5 shrink-0 text-amber-400" />
            <div className="space-y-1 text-sm">
              <p className="font-semibold text-amber-300">This is a template, not a policy.</p>
              <p>
                Replace this page before you launch. It describes what the code stores, so you have
                somewhere accurate to start, but it makes no promises on your behalf and is not
                legal advice.
              </p>
            </div>
          </div>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-primary">What this software stores</h2>
            <p>
              When you create an account, {APP_NAME} keeps your email address, your username and
              display name, and a hash of your password. The password itself is never stored — only
              an argon2id hash, which cannot be turned back into the original.
            </p>
            <p>Beyond that, it stores what you put into the app:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Your profile: bio, location, profile and banner images.</li>
              <li>Posts you upload, including the images themselves.</li>
              <li>Your ratings, follows and comments.</li>
              <li>Direct messages, in plain text, readable by whoever runs the server.</li>
              <li>Notifications generated by other people's activity.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-primary">Cookies</h2>
            <p>
              One cookie, named <code className="text-primary">sid</code>. It holds a signed session
              identifier and nothing else — no personal data travels in it. It is marked HttpOnly so
              scripts on the page cannot read it, SameSite=Lax so other sites cannot use it, and
              Secure whenever the app runs over HTTPS. It lasts 30 days, and signing out ends the
              session on the server as well as clearing the cookie.
            </p>
            <p>There is no analytics, advertising or tracking cookie in this codebase.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-primary">Who else sees it</h2>
            <p>
              Nothing in this code sends your data to a third party. It talks to one database, and
              whoever operates this deployment controls that database and can read everything in it,
              including private messages.
            </p>
            <p>
              Your profile, your posts and your position on the leaderboard are visible to anyone,
              signed in or not. Your messages and notifications are not.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-primary">What you need to add</h2>
            <p>Before launching, this page needs at least:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Who operates this service, and how to contact you.</li>
              <li>Where the data is hosted, and how long you keep it.</li>
              <li>How someone requests a copy of their data, or its deletion.</li>
              <li>Which laws apply to you — GDPR, CCPA and others each have requirements.</li>
              <li>Any service you add that this template does not have: analytics, email, payments.</li>
            </ul>
            <p>
              If real people will use your deployment, have someone qualified review it. A privacy
              policy is a legal document, and this page is not one.
            </p>
          </section>
        </CardContent>
      </Card>
    </div>
  );
};

export default PrivacyPolicy;
